export const POST_CUSTOMER = '/api/admin/v1/customers';
export const POST_CUSTOMER_ADVANCE_FILTERING = '/api/admin/v1/customers1';
export const GET_ALL_CUSTOMERS = '/api/admin/v1/customers?';

export const DELETE_CUSTOMERS = '/api/admin/v1/customers/';
export const UPDATE_CUSTOMER = '/api/admin/v1/customers/';

export const GET_COUNTIES = '/api/admin/v1/countries?paginate=false';

export const GET_PROFILE_DETAILS_BY_ID = '/api/admin/v1/customers/';
export const UPDATE_PROFILE_DETAILS_BY_ID = '/api/admin/v1/customers/';
export const SPECIFYING_CUSTOMER = '/api/admin/v1/customers/';
export const ADDRESSES = '/addresses/';
export const CUSTOM_ADDRESS = '/addresses';

export const FETCH_DETAILS_BY_SKU = '/api/admin/v1/items/';
export const UPDATE_GENERAL_DETAILS = '/api/admin/v1/items/';
export const UPDATE_VARIETY_DETAILS = '/api/admin/v1/advertisements/';
export const VARIATION = '/selections/';

export const GET_ALL_PRODUCT_LIST = '/api/admin/v1/advertisements?';
export const GET_ALL_ATTRIBUTE_LIST = '/api/admin/v1/item-attributes';
export const GET_ALL_ATTRIBUTE_LIST_PAGINATION = '/api/countries';
export const UPDATE_PRODUCT_ATTRIBUTE = '/api/admin/v1/items/';
export const GET_PRODUCT_BY_ID = '/api/admin/v1/items/';
export const CREATE_ATTRIBUTE = '/api/admin/v1/item-attributes';
export const UPDATE_ATTRIBUTE = '/api/admin/v1/item-attributes/';
export const GET_ALL_BOX_CHARGE = '/api/alert-types';
export const GET_ALL_CANCEL_ORDER_REASON = '/api/priorities';
export const GET_ALL_VEHICLES = '/api/vehicles';
export const GET_ALL_REPORT = '/api/reports';
export const GET_ALL_VEHICLE_SEARCH = '/api/vehicle-search/search';
export const UPDATE_CANCEL_ORDER_REASON = '/api/admin/v1/order-cancel-reasons/';
export const CREATE_CANCEL_ORDER_REASON = '/api/countries';
export const CREATE_CANCEL_ORDER_REASON1 = '/api/countries';
export const GET_ALL_UNIT_PRICE_CHARGE = '/api/admin/v1/unit-price-change-reasons?';
export const CREATE_UNIT_PRICE_CHARGE = '/api/admin/v1/unit-price-change-reasons';
export const UPDATE_UNIT_PRICE_CHARGE = '/api/admin/v1/unit-price-change-reasons/';
export const GET_ALL_PICKUP_OPTION = '/api/admin/v1/pickup-options?';
export const UPDATE_PICKUP_OPTION = '/api/admin/v1/pickup-options/';
export const CREATE_PICKUP_OPTION = '/api/admin/v1/pickup-options';
export const GET_ALL_ORDER_STATUS_MASTER = '/api/admin/v1/order-status?';
export const UPDATE_ORDER_STATUS_MASTER = '/api/admin/v1/order-status/';
export const CREATE_ORDER_STATUS_MASTER = '/api/admin/v1/order-status';
export const GET_ALL_CATEGORY_MANAGEMENT_LIST_PAGINATION = '/api/admin/v1/item-categories?';
export const CREATE_CATEGORY_MANAGEMENT = '/api/admin/v1/item-categories';
export const UPDATE_CATEGORY_MANAGEMENT = '/api/admin/v1/item-categories/';
export const GET_ALL_CATEGORY_MANAGEMENT_WITHOUT_PAGINATION = '/api/admin/v1/item-categories?paginate=false';
export const GET_ALL_UNIT_OF_MEASURE = '/api/admin/v1/unit-of-measures?paginate=false';
export const PUBLISHED_GENERAL_ADVERTISEMENT = '/api/admin/v1/advertisements/';
export const MEDIA_UPLOADING_FUNCTION = '/api/admin/v1/advertisements/';
export const CREATE_BOX_CHARGE = '/api/admin/v1/packing-material-charges';
export const ETF_ITEM_MASTER_DATA = '/api/admin/v1/master-datas?';
export const UPDATE_ETF_ITEM_MASTER_DATA = '/api/admin/v1/master-datas/';
export const UPLOAD_THUMBNAILS = '/api/admin/v1/advertisements/';
export const UPDATE_BOX_CHARGE = '/api/admin/v1/packing-material-charges/';
export const CREATE_PRODUCT_MASTER = '/api/admin/v1/items';
export const CREATE_GUARANTEE_OPTIONS = '/api/admin/v1/guarantee-options';
export const GET_ALL_GUARANTEE_OPTIONS = '/api/admin/v1/guarantee-options?';
export const UPDATE_GUARANTEE_OPTIONS = '/api/admin/v1/guarantee-options/';
export const ETF_ITEM_MASTER_DATA_WITHOUT_PAGINATION = '/api/admin/v1/master-datas?paginate=false';
export const ETF_ITEM_MASTER_DATA_WITH_PAGINATION = '/api/admin/v1/items?';
export const ETF_ITEM_UPDATE = '/api/admin/v1/items/';
export const DRIVERS_MASTER_DATA_WITH_PAGINATION = '/api/admin/v1/divers-den-items?';
export const CREATE_DRIVERS_MASTER_DATA = '/api/admin/v1/divers-den-items';
export const GET_DRIVERS_MASTER_DATA = '/api/admin/v1/divers-den-items/';
export const GET_ALL_GUARANTEE_OPTIONS_WITHOUT_PAGINATION = '/api/admin/v1/guarantee-options?paginate=false';
export const UPDATE_DRIVERS_DEN_ADVERTISEMENTS_DATA = '/api/admin/v1/divers-advertisements/';
export const GET_ALL_DRIVERS_DEN_ADVERTISEMENTS_DATA = '/api/admin/v1/divers-advertisements?';

export const PRODUCT_ITEM_REVIEWS = '/api/admin/v1/customer-reviews?';
export const UPDATE_PRODUCT_ITEM_REVIEWS = '/api/admin/v1/customer-reviews/';

export const ITEM_WISE_REVIEWS = '/api/admin/v1/reviews?';
export const UPDATE_ITEM_WISE_REVIEWS = '/api/admin/v1/reviews/';
export const SHOW_ITEM_WISE_REVIEWS = '/api/admin/v1/reviews/';
export const GET_ALL_PRODUCTS_WITHOUT_PAGINATION = '/api/admin/v1/products?paginate=false';
export const CREATE_DRIVERS_DEN_ADVERTISEMENTS = '/api/admin/v1/divers-advertisements';
export const UPDATE_DRIVERS_DEN_ADVERTISEMENTS_RELATED_PRODUCTS = '/api/admin/v1/advertisements/';

export const GET_RELATED_PRODUCTS = '/api/admin/v1/products';
export const TAG_RELATED_PRODUCTS = '/api/admin/v1/advertisements/';
export const TAG_RELATED_ARTICLES = '/api/admin/v1/advertisements/';
export const GET_ALL_RELATED_PRODUCT_ARTICLE = '/api/admin/v1/articles';
export const PUBLISH_DRIVERS_DEN_ADVERTISEMENTS = '/api/admin/v1/publish-advertisements';

export const GENERAL_ADVERTISEMENT_GUARANTEE_OPTIONS = '/api/admin/v1/advertisements/';
export const GET_ALL_SHIPPING_TYPES = '/api/admin/v1/shipping-types';
export const GET_ALL_PENDING_DRIVERS_DEN_ADVERTISEMENTS_DATA = '/api/admin/v1/pending-advertisements?';
export const UPDATE_SHIPPING_TYPE_STATUS = '/api/admin/v1/shipping-types/';
export const GET_ALL_CATEGORY_TYPES = '/api/admin/v1/item-categories?paginate=false';
export const DELETE_CATEGORY_TYPE = '/api/admin/v1/shipping-types/';
export const UPDATE_CATEGORY_TYPE = '/api/admin/v1/shipping-types/';
export const CREATE_CATEGORY_TYPE = '/api/admin/v1/shipping-types';

export const GET_ALL_SHIPPING_METHODS = '/api/admin/v1/shipping-methods?';
export const FETCH_ALL_SHIPPING_TYPES = '/api/admin/v1/shipping-types?paginate=false';
export const GET_SHIPPING_SCHEDULE_NAMES = '/api/admin/v1/shipping-schedules?paginate=false';
export const DELETE_SHIPPING_METHOD = '/api/admin/v1/shipping-methods/';
export const CREATE_SHIPPING_METHOD = '/api/admin/v1/shipping-methods';
export const UPDATE_SHIPPING_METHOD_STATUS = '/api/admin/v1/shipping-methods/';

export const SHIPPING_DELAYS = '/api/admin/v1/shipping-holds';
export const FETCH_AMERICAN_STATES = '/api/admin/v1/states';
export const CODE_GENERATOR = '/api/admin/v1/code-generators';

export const GET_ALL_HOLIDAYS = '/api/admin/v1/holiday-types';
export const CREATE_HOLIDAY = '/api/admin/v1/holidays';
export const UPDATE_HOLIDAY = '/api/admin/v1/holidays/';
export const GET_ALL_DATA_HOLIDAY_CAL = '/api/admin/v1/holidays?paginate=false';
export const CREATE_DIVERS_DEN_ITEM_DELETE_REASON = '/api/admin/v1/item-delete-reasons';
export const UPDATE_DIVERS_DEN_ITEM_DELETE_REASON = '/api/admin/v1/item-delete-reasons/';
export const GET_ALL_DIVERS_DEN_ITEM_DELETE_REASON_WITH_PAGINATION = '/api/admin/v1/item-delete-reasons?';
export const GET_ALL_DIVERS_DEN_ITEM_DELETE_REASON_WITHOUT_PAGINATION =
	'/api/admin/v1/item-delete-reasons?paginate=false';
export const ADVANCE_FILTERING_ETF_MASTER_DATA = '/api/admin/v1/master-datas?filter=';
export const CREATE_ARTICLE_CATEGORIES = '/api/admin/v1/article-categories';
export const GET_ALL_ARTICLE_CATEGORIES_WITH_PAGINATION = '/api/admin/v1/article-categories?';
export const UPDATE_ARTICLE_CATEGORIES = '/api/admin/v1/article-categories/';
export const GET_ALL_ARTICLE_CATEGORIES_WITHOUT_PAGINATION = '/api/admin/v1/article-categories?paginate=false';
export const CREATE_ARTICLE = '/api/admin/v1/articles';
export const GET_ALL_ARTICLE_WITH_PAGINATION = '/api/admin/v1/articles?';
export const UPDATE_ARTICLE = '/api/admin/v1/articles/';
export const GET_ALL_ARTICLE_WITHOUT_PAGINATION = '/api/admin/v1/articles?paginate=false';
export const ADVANCE_FILTERING_ARTICLE_DATA = '/api/admin/v1/articles?filter=';
export const ADVANCE_FILTERING_ARTICLE_CATEGORIES_DATA = '/api/admin/v1/article-categories?filter=';
export const ADVANCE_FILTERING_ITEM_CATEGORIES_DATA = '/api/admin/v1/item-categories?filter=';
export const ADVANCE_FILTERING_PRODUCT_MASTER_DATA = '/api/admin/v1/items?filter=';
export const ADVANCE_FILTERING_DIVERS_DEN_MASTER_DATA = '/api/admin/v1/divers-den-items?filter=';
export const ADVANCE_FILTERING_CUSTOMER_DATA = '/api/admin/v1/customers?filter=';
export const GENERAL_ADVERTISEMENT_REJECT = '/api/admin/v1/check-advertisement/';
export const ADVANCE_FILTERING_GENERAL_ADVERTISEMENT = '/api/admin/v1/advertisements?filter=';
export const ADVANCE_FILTERING_DIVERS_DEN_ADVERTISEMENT = '/api/admin/v1/divers-advertisements?filter=';
export const ADVANCE_FILTERING_DIVERS_DEN_PENDING_ADVERTISEMENT = '/api/admin/v1/pending-advertisements?filter=';
export const ADVANCE_FILTERING_ATTRIBUTE_ADVERTISEMENT = '/api/admin/v1/item-attributes?filter=';
export const GET_ALL_PUBLISH_PRODUCT_LIST = '/api/admin/v1/pending-general-advertisement?';
export const ADVANCE_FILTERING_GENERAL_ADVERTISEMENT_PUBLISH = '/api/admin/v1/pending-general-advertisement?filter=';
export const GET_ALL_ATTRIBUTE_LIST_WITHOUT_PAGINATION = '/api/admin/v1/item-attributes?paginate=false';
export const ENABLE_SUBSCRIBES_SERVICE = '/api/admin/v1/subscribes';
export const UPDATE_GENERAL_ADD = '/api/admin/v1/advertisements/';
